### ISSUE TITLE
error in code: empty(); Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by maroagobe** [gowondesigns/getter#1]
Fatal error: Can't use function return value in write context in C:\xampp\htdocs\magwox\mags\downloadx.php on line 399

**Comment by gowon** [comment]
There's a limitation in what empty() can accept as input in PHP < 5.5. All of the places that function is used needs to be updated handle those comparisons in a version-neutral way. 

References:
- http://stackoverflow.com/questions/17139264/cant-use-function-return-value-in-write-context
- http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context/4328049#4328049
